### PR TITLE
Adds support for custom destination file template

### PR DESCRIPTION
**Pull request by AndreaPaciolla**
I found out your module and I made an adaption to support some other usages by giving a custom template row.

### CODE REVIEW

**Comment by cjroth** [comment]
Hey, thanks for the PR.

I understand your use case, but I think it needs a few more things. In the readme, gulp-filelist is described "Convert list of file paths in current stream to a JSON file." This needs to be changed to make it clear that it's not just JSON files anymore. Also, I would recommend not hardwiring `\r\n` and rather including that in the custom template. Perhaps someone doesn't want it include return carriages.

Also, there need to be tests for this.

**Comment by AndreaPaciolla** [comment]
Hello @cjroth ,
you're right. Just implemented modifications you proposed as per SemVer indications.

**Comment by cjroth** [comment]
Hi, I'm a little confused by your test - why is it outputting a JSON file in XML syntax and then trying to require it as if it were JSON? The test is not passing.

**Comment by AndreaPaciolla** [comment]
@cjroth it was my fault, sorry for the slip. Fixed, merged and pushed out.

**Comment by cjroth** [comment]
Looks good! Thank you for adding this!

**Pull request merged**
