### PR TITLE
Add option to flatten file paths and bump version to 0.3.0

### PR DESCRIPTION
**Pull request by spacedawwwg**

### CODE REVIEW

**Comment by spacedawwwg** [comment]
Any opinion on whether this may get merged?

**Comment by cjroth** [comment]
Thanks for the contribution :)

**Comment by spacedawwwg** [comment]
No worries. Any chance of it being published to NPM (I'm still linking to my fork on github at the moment).

**Comment by cjroth** [comment]
Oops good point. Published. Thanks!

**Pull request merged**
